In [27]:
import numpy as np

In [28]:
# creation of numpy array
x = np.array([1, 2, 3, 4, 5])
print(x)
print(type(x)) # ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [29]:
print(x.size) #total no of elements
print(x.shape) # dimension wise elements
print(x.ndim) # num of dimension

5
(5,)
1


In [30]:
x2d = np.array([[1, 2, 3 ],[4, 5, 6]])
print(x2d)
 # shape and size
print(x2d.size) 
print(x2d.shape)
print(x2d.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [31]:
x25 = np.random.randint(1,100, (5,5))
print(x25)

[[68 82 50 57 14]
 [ 6 77 48 69 77]
 [67 81 20 89 92]
 [78 40  1 68 77]
 [29  5 12  3 30]]


In [32]:
xseq1 = np.arange(1, 101, 4)
print(xseq1.size,"elements")
print("=>1D MATRIX")
print("1D MATRIX RESHAPED TO 2D")
print(xseq1.reshape(5,5))

25 elements
=>1D MATRIX
1D MATRIX RESHAPED TO 2D
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [33]:
xseq2 = np.linspace(1, 100, 50)
print(xseq2.size,"elements")
print("=>1D MATRIX")
print(xseq2)
print("=>1D MATRIX RESHAPED TO 2D")
print(xseq2.reshape(10,5))
print("=>1D MATRIX RESHAPED TO 3D")
print(xseq2.reshape(5,5,2))


50 elements
=>1D MATRIX
[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
=>1D MATRIX RESHAPED TO 2D
[[  1.           3.02040816   5.04081633   7.06122449   9.08163265]
 [ 11.10204082  13.12244898  15.14285714  17.16326531  19.18367347]
 [ 21.20408163  23.2244898   25.24489796  27.26530612  29.28571429]
 [ 31.30612245  33.32653061  35.34693878  37.36734694  39.3877551 ]
 [ 41.40816327  4


print(xseq2d)

In [34]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

- indexing and slicing

- boolean filter
- maths and starts
- methods

In [35]:
x25

array([[68, 82, 50, 57, 14],
       [ 6, 77, 48, 69, 77],
       [67, 81, 20, 89, 92],
       [78, 40,  1, 68, 77],
       [29,  5, 12,  3, 30]])

In [36]:
# first row
print(x25[0])

[68 82 50 57 14]


In [37]:
# last row
print(x25[-1])

[29  5 12  3 30]


In [38]:
# single element
print(x25[0,1]) # some as print(x25[0][1])

82


In [39]:
# 1st columns
print(x25[:,0])

# sec columns
print(x25[:,1])

# third columns
print(x25[:,-1])


[68  6 67 78 29]
[82 77 81 40  5]
[14 77 92 77 30]


In [40]:
# col 0 and 1 idxs
print(x25[:, [0,1]])

[[68 82]
 [ 6 77]
 [67 81]
 [78 40]
 [29  5]]


In [41]:
# column o , 1 , 2 idix
print(x25[:,[0,1,2]])
# same thing as above
print(x25[:, :3])


[[68 82 50]
 [ 6 77 48]
 [67 81 20]
 [78 40  1]
 [29  5 12]]
[[68 82 50]
 [ 6 77 48]
 [67 81 20]
 [78 40  1]
 [29  5 12]]


In [42]:
# filtering data without numpy bollean filter (bad idea)
for i in x25:
    for j in i:
        if j <= 20:
            print(j)

14
6
20
1
5
12
3


In [43]:
x25 <= 20 # boolean filter

array([[False, False, False, False,  True],
       [ True, False, False, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True, False]])

In [44]:
x25[x25 <= 20]

array([14,  6, 20,  1,  5, 12,  3])

In [45]:
x25[x25 > 50]

array([68, 82, 57, 77, 69, 77, 67, 81, 89, 92, 78, 68, 77])

In [46]:
(x25 > 20) & (x25 < 70)

array([[ True, False,  True,  True, False],
       [False, False,  True,  True, False],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [ True, False, False, False,  True]])

In [47]:
x25[(x25 > 20) & (x25 < 70)]

array([68, 50, 57, 48, 69, 67, 40, 68, 29, 30])

In [53]:
np.append(x25, [1,2,3,4,5,6]) # not as expected, but work 

array([68, 82, 50, 57, 14,  6, 77, 48, 69, 77, 67, 81, 20, 89, 92, 78, 40,
        1, 68, 77, 29,  5, 12,  3, 30,  1,  2,  3,  4,  5,  6])

In [48]:
np.append(x25, np.array([[1, 2, 3, 4, 5, ]]),axis=0) # not as expected , but work

array([[68, 82, 50, 57, 14],
       [ 6, 77, 48, 69, 77],
       [67, 81, 20, 89, 92],
       [78, 40,  1, 68, 77],
       [29,  5, 12,  3, 30],
       [ 1,  2,  3,  4,  5]])

In [49]:
x25

array([[68, 82, 50, 57, 14],
       [ 6, 77, 48, 69, 77],
       [67, 81, 20, 89, 92],
       [78, 40,  1, 68, 77],
       [29,  5, 12,  3, 30]])

In [55]:
a = np.random.randint(1,100,(3,2))
b = np.random.randint(1,100,(2,3))

In [56]:
print(a.shape)
print(b.shape)

(3, 2)
(2, 3)


In [57]:
a.T # same as a.transpose()

array([[16, 70, 57],
       [80, 84, 80]])

In [58]:
print(np.hstack((a,b.T)))

[[16 80 65  7]
 [70 84 70 19]
 [57 80 85 17]]


In [59]:
print(np.hstack((a.T,b)))

[[16 70 57 65 70 85]
 [80 84 80  7 19 17]]


In [60]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x)
print()
print(y)

[[8 8 2]
 [1 7 8]
 [7 4 5]]

[[7 4 4]
 [4 7 2]
 [2 3 5]]


In [67]:
print('add') 
print(x+y) # addition
print('sub') 
print(x-y) # substraction
print('div') 
print(x/y) # divide
print('element wise multiplication ') 
print(x*y) # element wise multiplication
print('element wise mod')
print(x%y)

add
[[15 12  6]
 [ 5 14 10]
 [ 9  7 10]]
sub
[[ 1  4 -2]
 [-3  0  6]
 [ 5  1  0]]
div
[[1.14285714 2.         0.5       ]
 [0.25       1.         4.        ]
 [3.5        1.33333333 1.        ]]
element wise multiplication 
[[56 32  8]
 [ 4 49 16]
 [14 12 25]]
element wise mod
[[1 0 2]
 [1 0 0]
 [1 1 0]]


In [68]:
print(x.dot(y)) # mat multiplication

[[92 94 58]
 [51 77 58]
 [75 71 61]]


In [70]:
x.sum()

50

In [62]:
x.sum(axis=0) # row wise sum

array([16, 19, 15])

In [63]:
x.sum(axis=1) 

array([18, 16, 16])

In [64]:
print(x.mean()) # all
print(x.mean(axis=0)) # row
print(x.mean(axis=1)) # col

5.555555555555555
[5.33333333 6.33333333 5.        ]
[6.         5.33333333 5.33333333]


In [65]:
print(x.max()) # max val
print(x.min()) # min val
print(x.argmax())# index of max val
print(x.argmin()) # index of min val
print(x.flatten()[4])# ac essing are called using np acialble through the variable

8
1
0
3
7


In [66]:
np.median(x)

7.0